const JP_REDUCER = {
  SET_TYPE: "SET_TYPE",
  SET_Q: "SET_Q",
  SET_PAGE: "SET_PAGE",
  SET_GENRE: "SET_GENRE",
  REMOVE_GENRE: "REMOVE_GENRE",
};
const JP_TYPES = [
  { name: "Anime" },
  { name: "Manga" },
  { name: "Character" },
  { name: "Person" },
];
const JP_UNITS = {
  anime: "Anime",
  manga: "Manga",
  shared: "Shared",
};
const JP_ANIME_GENRES = [
  { id: 1, name: "Action", id_api: 1 },
  { id: 2, name: "Adventure", id_api: 2 },
  { id: 3, name: "Cars", id_api: 3 },
  { id: 4, name: "Comedy", id_api: 4 },
  { id: 5, name: "Avante Garde", id_api: 5 },
  { id: 6, name: "Demons", id_api: 6 },
  { id: 7, name: "Mystery", id_api: 7 },
  { id: 8, name: "Drama", id_api: 8 },
  { id: 9, name: "Ecchi", id_api: 9 },
  { id: 10, name: "Fantasy", id_api: 10 },
  { id: 11, name: "Game", id_api: 11 },
  { id: 12, name: "Hentai", id_api: 12 },
  { id: 13, name: "Historical", id_api: 13 },
  { id: 14, name: "Horror", id_api: 14 },
  { id: 15, name: "Kid_apis", id_api: 15 },
  { id: 16, name: "Martial Arts", id_api: 17 },
  { id: 17, name: "Mecha", id_api: 18 },
  { id: 18, name: "Music", id_api: 19 },
  { id: 19, name: "Parody", id_api: 20 },
  { id: 20, name: "Samurai", id_api: 21 },
  { id: 21, name: "Romance", id_api: 22 },
  { id: 22, name: "School", id_api: 23 },
  { id: 23, name: "Sci Fi", id_api: 24 },
  { id: 24, name: "Shoujo", id_api: 25 },
  { id: 25, name: "Girls Love", id_api: 26 },
  { id: 26, name: "Shounen", id_api: 27 },
  { id: 27, name: "Boys Love", id_api: 28 },
  { id: 28, name: "Space", id_api: 29 },
  { id: 29, name: "Sports", id_api: 30 },
  { id: 30, name: "Super Power", id_api: 31 },
  { id: 31, name: "Vampire", id_api: 32 },
  { id: 32, name: "Harem", id_api: 35 },
  { id: 33, name: "Slice Of Life", id_api: 36 },
  { id: 34, name: "Supernatural", id_api: 37 },
  { id: 35, name: "Military", id_api: 38 },
  { id: 36, name: "Police", id_api: 39 },
  { id: 37, name: "Psychological", id_api: 40 },
  { id: 38, name: "Award Winning", id_api: 46 },
  { id: 39, name: "Gourmet", id_api: 47 },
  { id: 40, name: "Work Life", id_api: 48 },
  { id: 41, name: "Erotica", id_api: 49 },
  { id: 42, name: "Suspense", id_api: 41 },
  { id: 43, name: "Seinen", id_api: 42 },
  { id: 44, name: "Josei", id_api: 43 },
];
const JP_MANGA_GENRES = [
  { id: 1, name: "Action", id_api: 1 },
  { id: 2, name: "Adventure", id_api: 2 },
  { id: 3, name: "Cars", id_api: 3 },
  { id: 4, name: "Comedy", id_api: 4 },
  { id: 5, name: "Avante Garde", id_api: 5 },
  { id: 6, name: "Demons", id_api: 6 },
  { id: 7, name: "Mystery", id_api: 7 },
  { id: 8, name: "Drama", id_api: 8 },
  { id: 9, name: "Ecchi", id_api: 9 },
  { id: 10, name: "Fantasy", id_api: 10 },
  { id: 11, name: "Game", id_api: 11 },
  { id: 12, name: "Hentai", id_api: 12 },
  { id: 13, name: "Historical", id_api: 13 },
  { id: 14, name: "Horror", id_api: 14 },
  { id: 15, name: "Kid_apis", id_api: 15 },
  { id: 16, name: "Martial Arts", id_api: 17 },
  { id: 17, name: "Mecha", id_api: 18 },
  { id: 18, name: "Music", id_api: 19 },
  { id: 19, name: "Parody", id_api: 20 },
  { id: 20, name: "Samurai", id_api: 21 },
  { id: 21, name: "Romance", id_api: 22 },
  { id: 22, name: "School", id_api: 23 },
  { id: 23, name: "Sci Fi", id_api: 24 },
  { id: 24, name: "Shoujo", id_api: 25 },
  { id: 25, name: "Girls Love", id_api: 26 },
  { id: 26, name: "Shounen", id_api: 27 },
  { id: 27, name: "Boys Love", id_api: 28 },
  { id: 28, name: "Space", id_api: 29 },
  { id: 29, name: "Sports", id_api: 30 },
  { id: 30, name: "Super Power", id_api: 31 },
  { id: 31, name: "Vampire", id_api: 32 },
  { id: 32, name: "Harem", id_api: 35 },
  { id: 33, name: "Slice Of Life", id_api: 36 },
  { id: 34, name: "Supernatural", id_api: 37 },
  { id: 35, name: "Military", id_api: 38 },
  { id: 36, name: "Police", id_api: 39 },
  { id: 37, name: "Psychological", id_api: 40 },
  { id: 38, name: "Award Winning", id_api: 46 },
  { id: 39, name: "Gourmet", id_api: 47 },
  { id: 40, name: "Work Life", id_api: 48 },
  { id: 41, name: "Erotica", id_api: 49 },
  { id: 45, name: "Seinen", id_api: 41 },
  { id: 46, name: "Josei", id_api: 42 },
  { id: 47, name: "Doujinshi", id_api: 43 },
  { id: 48, name: "Gender Bender", id_api: 44 },
  { id: 49, name: "Suspense", id_api: 45 },
];

export { JP_REDUCER, JP_ANIME_GENRES, JP_MANGA_GENRES, JP_TYPES, JP_UNITS };
