const CONST_JAP = {
  SET_TYPE: "SET_TYPE",
  SET_Q: "SET_Q",
  SET_PAGE: "SET_PAGE",
  SET_GENRE: "SET_GENRE",
  anime: "Anime",
  manga: "Manga",
  genres: {
    shared: [
      { name: "Action", id: 1 },
      { name: "Adventure", id: 2 },
      { name: "Cars", id: 3 },
      { name: "Comedy", id: 4 },
      { name: "Avante Garde", id: 5 },
      { name: "Demons", id: 6 },
      { name: "Mystery", id: 7 },
      { name: "Drama", id: 8 },
      { name: "Ecchi", id: 9 },
      { name: "Fantasy", id: 10 },
      { name: "Game", id: 11 },
      { name: "Hentai", id: 12 },
      { name: "Historical", id: 13 },
      { name: "Horror", id: 14 },
      { name: "Kids", id: 15 },
      { name: "Martial Arts", id: 17 },
      { name: "Mecha", id: 18 },
      { name: "Music", id: 19 },
      { name: "Parody", id: 20 },
      { name: "Samurai", id: 21 },
      { name: "Romance", id: 22 },
      { name: "School", id: 23 },
      { name: "Sci Fi", id: 24 },
      { name: "Shoujo", id: 25 },
      { name: "Girls Love", id: 26 },
      { name: "Shounen", id: 27 },
      { name: "Boys Love", id: 28 },
      { name: "Space", id: 29 },
      { name: "Sports", id: 30 },
      { name: "Super Power", id: 31 },
      { name: "Vampire", id: 32 },
      { name: "Harem", id: 35 },
      { name: "Slice Of Life", id: 36 },
      { name: "Supernatural", id: 37 },
      { name: "Military", id: 38 },
      { name: "Police", id: 39 },
      { name: "Psychological", id: 40 },
      { name: "Award Winning", id: 46 },
      { name: "Gourmet", id: 47 },
      { name: "Work Life", id: 48 },
      { name: "Erotica", id: 49 },
    ],
    anime: [
      { name: "Suspense", id: 41 },
      { name: "Seinen", id: 42 },
      { name: "Josei", id: 43 },
    ],
    manga: [
      { name: "Seinen", id: 41 },
      { name: "Josei", id: 42 },
      { name: "Doujinshi", id: 43 },
      { name: "Gender Bender", id: 44 },
      { name: "Suspense", id: 45 },
    ],
  },
  types: [
    { name: "Anime" },
    { name: "Manga" },
    { name: "Character" },
    { name: "Person" },
  ],
};
export default CONST_JAP;
